### ISSUE TITLE
US 01.08.01: View map of user check-ins

### ISSUE THREAD

**Issue by kaylemnicee** [CMPUT301W24T59/ScanSaga#14]
As an organizer, I want to see on a map where users are checking in from.

### **Description**
Organizers seek to visualize on a map the locations from which users are checking in. This feature provides geographical insights into event participation, helping in targeting specific demographics and enhancing event planning and marketing strategies.

### **Acceptance Criteria**

- [x] - The organizer dashboard includes a map feature displaying user check-in locations.
- [x] - Organizers can view the distribution of check-in locations in real-time.
- [x] - The map provides detailed information about the concentration and frequency of check-ins from different geographical regions.
### **Tasks**
- [x] [CMPUT301W24T59/ScanSaga/issues/49]
- [x] [CMPUT301W24T59/ScanSaga/issues/47 ]
