### ISSUE TITLE
US 02.02.02: Remove profile pictures

### ISSUE THREAD

**Issue by kaylemnicee** [CMPUT301W24T59/ScanSaga#18]
As an attendee, I need the ability to remove profile pictures if needed.

### **Description**

Attendees require the capability to remove profile pictures from their profiles when necessary. This provides flexibility in managing profile information and privacy preferences, allowing attendees to control the visibility of their images.

### **Acceptance Criteria**

- [x] - A user-friendly interface is available for attendees to remove their profile pictures.
- [x] - Attendees can easily locate and access the option to remove their profile pictures.
- [x] - Upon removal, the profile picture is no longer displayed in the attendee's profile.

### **Tasks**

- [x] #81
- [x] #82
- [x] #83
