### ISSUE TITLE
US 01.01.02 Reuse an existing QR code

### ISSUE THREAD

**Issue by rosybudhathoki** [CMPUT301W24T59/ScanSaga#6]
As an organizer, I want the option to reuse an existing QR code for attendee check-ins.

### **Description**
Organizers require the flexibility to reuse existing QR codes for attendee check-ins. This feature streamlines event management by allowing organizers to use familiar QR codes for multiple events or instances, reducing the need to generate new codes for each event and simplifying attendee check-in processes.

### **Acceptance Criteria**

- [x] - There is a feature in the organizer dashboard to reuse existing QR codes for attendee check-ins.
- [x] - Organizers can select and assign an existing QR code to a new event.
- [x] - The reused QR code remains functional for attendee check-ins and retains its original linkages and functionalities.

### **Tasks**
- [x] [CMPUT301W24T59/ScanSaga/issues/6]
- [x] [CMPUT301W24T59/ScanSaga/issues/38]
